---
- name: Add repository key for jenkins
  apt_key: url={{ jenkins_public_key_url }} state=present

- name: Add jenkins repository
  apt_repository: repo={{ jenkins_repo }} state=present update_cache=yes

- name: Installing jenkis with all dependencies
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items: '{{ jenkins_packages }}'

- name: Ensure that jenkins service is running
  service: name=jenkins state=started enabled=yes

- name: Add user mod of docker for jenkins user
  command: usermod -aG docker jenkins

- name: Restart Jenkins service
  service: name=jenkins state=restarted enabled=yes

- name: Wiating on file /var/lib/jenkins/secrets/initialAdminPassword
  wait_for:
    path: /var/lib/jenkins/secrets/initialAdminPassword
    state: present

- name: Printing Jenkins default administration password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_default_admin_password

- debug:
    msg: "Jenkins Initial Admin Password:  {{ jenkins_default_admin_password.stdout }} "
    